### ISSUE TITLE
Release v0.0.2

### ISSUE THREAD

**Issue by ryanc** [octodns/octodns-ultra#10]
Hello,

Would it be possible to tag and release v0.0.2? The UltraDNS zone API (v2) is no longer returning the "resultInfo" key in the response and generates the following error. This was fixed in #2. Thank you.

```
2022-10-10T14:04:55  [139672593020480] INFO  Ns1Provider[ns1] plan: desired=example.com.
Traceback (most recent call last):
  File "/home/rcavicchioni/projects/dns/venv/bin/octodns-sync", line 8, in <module>
2022-10-10T14:04:55  [139672601413184] INFO  YamlProvider[config] populate:   found 3 records, exists=False
2022-10-10T14:04:55  [139672601413184] INFO  Ns1Provider[ns1] plan: desired=example.com.
    sys.exit(main())
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns/cmds/sync.py", line 64, in main
    manager.sync(
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns/manager.py", line 550, in sync
    ps, d = future.result()
  File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns/manager.py", line 387, in _populate_and_plan
    plan = target.plan(zone, processors=processors)
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns/provider/base.py", line 185, in plan
    exists = self.populate(existing, target=True, lenient=True)
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns_ultra/__init__.py", line 280, in populate
    records = self.zone_records(zone)
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns_ultra/__init__.py", line 246, in zone_records
    if zone.name not in self.zones:
  File "/home/rcavicchioni/projects/dns/venv/lib64/python3.10/site-packages/octodns_ultra/__init__.py", line 166, in zones
    info = resp['resultInfo']
KeyError: 'resultInfo'
```

**Comment by ross** [comment]
Sure. Will cut a release shortly.

**Comment by ryanc** [comment]
Thank you. I appreciate it.
